site_name: Themis
theme: material
nav:
  - Introduction: index.md
  - Getting Started:
    - Local Setup: getting_started/local_setup.md
    - Quick Start:
      - Permit All: getting_started/quick_start/permit_all.md
  - Policy File: policy_file/policy_file.md
  - Algorithms: algorithms/algo.md
  - Components:
    - PDP: components/pdp.md
    - PIP: components/pip.md
    - pap: components/pap.md
